### ISSUE TITLE
Device specific animations

### ISSUE THREAD

**Issue by ReinhardSchmidt** [hoprnet/bounties-hoprnet-org#12]
#CURRENTLY
  The animation on desktop looks nice, but on Tablet and specially mobile it can be further optimized. We therefore created a specific asset for Tablet and mobile, and want to separate the circle in general from the animation (it's currently included).
  

FIGMA: https://www.figma.com/file/cW2s7yBpDIDXNjUce1tdpK/hopr_Token_Website_43_Bounty-SLIGHT_UPDATES
![Bildschirmfoto 2022-05-25 um 13 13 56](https://user-images.githubusercontent.com/78225531/170250123-0931378a-409f-43e7-a6e2-4a308053ce23.png)

- Yellow circle, use the svg or eps (main-folder): 
https://drive.google.com/open?id=1wJZseXJIBIXKK5AzvCvbGqg1OPF5YKM2&authuser=zrh%40hoprnet.org&usp=drive_fs

- Desktop-Animation, "anim_three_robots.json"
https://drive.google.com/drive/folders/1wJZseXJIBIXKK5AzvCvbGqg1OPF5YKM2?usp=sharing

- Mobile-Animation, "anim_two_robots.json": 
https://drive.google.com/open?id=1wVBwv1PUK40cOCACOXpKyWX8yNzR9x7U&authuser=zrh%40hoprnet.org&usp=drive_fs

- Tablet-Animation: use the desktop asset, see for yourself if it works - if not, use the Mobile-asset.

@nionis: the asset were just ready by now. Sorry for this late-coming issue.

**Comment by mjadach-iv** [comment]
Closed as this project is not used for now.
