### ISSUE TITLE
Add more newbie onboarding materials

### ISSUE THREAD

**Issue by SCBuergel** [hoprnet/bounties-hoprnet-org#16]
As a total Ethereum newbie, I want to learn how various things work, so that I can earn money and contribute to the HOPR ecosystem.

Ideas for docs / links
- introduction to Ethereum / the EVM (fallback: link to Ethereum yellow paper, complex and not too much developer focus but comprehensive)
- getting started with Dune Analytics (fallback: link to Dune docs, they're good)
- How to setup a wallet (fallback: link to Metamask docs, not great but ok-ish)

**Comment by mjadach-iv** [comment]
Closed as this project is not used for now.
